src/Model/Module.php, src/Steps/Release/TagModules.php
This is necessary so that `cow release:publish` can be resumed if (for instance) a packagist error failed to find the newly tagged release.
=> API Skip existing tags so that failed publishes can be safely resumed

src/Commands/Branch/Checkout.php
Without this asset-admin wasn't being checked out properly, as it has the `^1` constraint.
=> API checkout:branch now includes modules that aren't self.version

src/Steps/Release/UpdateTranslations.php
A trailing newline in $results was causing version_compare to act weird. Also the logic was backwards.
=> BUG Fix transifex version check logic

src/Commands/Module/Tag.php, src/Steps/Module/TagAnnotatedModule.php
This adds the ability to set the title of the tag much like you would if tagging by hand.
Rather than releases always being named the same as their tag name, we can name them independently if we want to - this is useful for bug fix tags.
eg: `cow module:tag blog 2.4.4 -m 'Casting fixes'` would result in a tag 2.4.4 but with the release title "Casting fixes"
=> NEW Allow release title to be set

src/Steps/Release/RewriteReleaseBranches.php
In response to 4.0.0-alpha3 creating a phantom `4.0` branch in installer (but thankfully no other modules).
=> BUG Prevent alpha releases creating new branches

composer.json
php-http/guzzle6-adapter:^1.2 is not a tagged release - analysing the [diff between 1.1 and dev-master (1.2.x-dev)](https://github.com/php-http/guzzle6-adapter/compare/v1.1.1...master) it's only changes to tests at the moment.
This change allows default global installation to work (without having to globally allow dev deps).
=> Update to stable requirments

src/Model/Release/ComposerConstraint.php, tests/Model/Release/ComposerConstraintTest.php
=> BUG Fix changelog generation failing on exact historic version constraint

src/Model/Release/ComposerConstraint.php, tests/Model/Release/ComposerConstraintTest.php
Came about when we tried releasing silverstripe/framework which has a `^1@dev` dependency on `silverstripe/config`.
@dhensby can you look at this please? The tests should more or less explain the use case.
=> BUG Missing support for semver @dev dependencies

src/Model/Changelog/Changelog.php, src/Model/Changelog/ChangelogItem.php
It's still not perfect, but greatly reduces duplicates of commits merged up from lower branches.
=> ENHANCEMENT Prevent duplicate changelog commits

readme.md
By default the dev version of  php-http/guzzle6-adapter that cow relies on won't be pulled in. Explicitly installing php-`http/guzzle6-adapter:1.2.x-dev` addresses this.
=> Address quirk in  install docs

composer.json, readme.md
According to https://github.com/php-http/guzzle6-adapter/compare/v1.1.1...master there's nothing in master branch that isn't available in 1.1.1.
=> Adjust guzzle dep to 1.1.1

readme.md, src/Commands/Release/Branch.php, src/Commands/Release/Changelog.php, src/Commands/Release/Plan.php, src/Commands/Release/Release.php, src/Commands/Release/Translate.php, src/Model/Modules/Library.php, src/Model/Modules/Module.php, src/Model/Modules/Project.php, src/Model/Release/LibraryRelease.php, src/Steps/Release/PlanRelease.php, src/Steps/Release/RewriteReleaseBranches.php, src/Steps/Release/UpdateTranslations.php, src/Steps/Step.php
Rebased on top of https://github.com/silverstripe/cow/pull/57
Fixes #53 
You can specify branching via a `--branching` option, which is saved into the release plan. You can also modify this value at the planning stage.
=> API Implement vendor modules / branch strategy

src/Model/Modules/Library.php, src/Model/Release/Version.php, src/Steps/Release/CreateChangelog.php
Fixes https://github.com/silverstripe/cow/issues/63
Also fixes bug in changelog generation skipping heaps of modules.
I've traced the bug to Library::getHistoryComposerData() only treating composer requires as specific version tags, not loose constraints.
=> BUG Fix changelog generation / initial plan generation

cow-schema.md, cow.schema.json
Fixes regression in child-stability-inherit, which should be an array of strings or a boolean.
Fixes #70
=> FIX Regression in child-stability-inherit: accepts boolean or array of strings

readme.md, src/Application.php, src/Commands/Command.php, src/Commands/Schema/Validate.php, src/Model/Modules/Library.php, src/Utility/Config.php, src/Utility/SchemaValidator.php, tests/Utility/SchemaValidatorTest.php
This pull request adds a SchemaValidator utility class and adds a new `schema:validate` command.
Also now returning the exit code from Command to ensure we can check for schema validation failures via exit code 1 in CI builds (when this command makes it into CI!).
Resolves #68
=> NEW Add schema:validate command and return command exit code

src/Application.php
Trying to install and run cow on an Ubuntu system I was greeted by a fatal error "can't find class ChangeLog" - which was caused by the differences between the class name call of `ChangeLog` and the class name (and thus filename) being `Changelog.php`. Correcting this single erroneous reference has fixed the issue.
=> FIX stop autoload failure on case sensitive system

src/Model/Modules/Library.php
`git pull origin master --rebase` causes an error with unknown option 'rebase', however it _is_ a thing, but it must be specified as `git pull --rebase origin master`, so update `cow` to use this syntax instead.
=> FIX order of arguments to git-pull is important

src/Steps/Release/CreateProject.php
Fixes issue when using a custom repository during `cow release:create`:
```
[create project] Reverting installer changes to composer.json
PHP Warning:  file_put_contents(.../dev/releases/release-silverstripe_installer-1.2.3/composer.json/.cow.repository): failed to open stream: No such file or directory in .../.composer/vendor/silverstripe/cow/src/Steps/Release/CreateProject.php on line 97
```
=> FIX Use correct repository path for .cow.repository writing

src/Commands/Release/Release.php, src/Model/Modules/Library.php, src/Model/Modules/Project.php, src/Steps/Release/CreateProject.php
After you've initially created the plan you don't really need to keep fetching tags each time.
It's important that it defaults to doing so when you are first creating the plan, but after that it doesn't need to.
You may also not want to fetch tags during plan generation if you're just tweaking a couple of versions.
This PR adds a `--skip-fetch-tags` option which will do that.
Resolves #77
=> NEW Add --skip-fetch-tags option to skip fetching tags from origin during plan creation

src/Application.php, src/Commands/Release/Release.php
At the moment the recommended next command when finishing `cow release` always shows to run `cow release:tag` even if you're running cow via some other path.
This fixes that.
=> NEW Make sure cow outputs the correct bin name when giving commands

bin/cow
Throwing an Exception this early is really horrible as the console library hasn't booted and so raw output is written to the console as text. The output message also wasn't so helpful.
Old output on failure:
```
PHP Fatal error:  Uncaught RuntimeException: What is Composer? Is a food? in /Users/dhensby/projects/releases/cow/bin/cow:27
Stack trace:
#0 {main}
thrown in /Users/dhensby/projects/releases/cow/bin/cow on line 27
Fatal error: Uncaught RuntimeException: What is Composer? Is a food? in /Users/dhensby/projects/releases/cow/bin/cow:27
Stack trace:
#0 {main}
thrown in /Users/dhensby/projects/releases/cow/bin/cow on line 27
```
New output on failure:
```
cow was unable to locate the vendor/autoload.php file.
Please make sure you've installed the composer dependencies by running …
```
=> FIX A nicer error when vendor/autoload.php isn't found

src/Application.php
I've yet to figure out why, but on my Mac OS system `file_exists` will always return false. This results in an infinite loop because `dirname('/') === '/'`
=> FIX Prevent infinite loops when looking for installed.json

src/Application.php
Sometimes the installed.json file won't contain `silverstripe/cow` (specifically when you haven't installed globally).
We shouldn't continue to look for the file once it's been found.
=> Dont keep looking for vendor/composer/installed.json once its found

src/Model/Changelog/Changelog.php, src/Model/Changelog/ChangelogItem.php, tests/Model/Changelog/ChangelogItemTest.php
For example, "Fixing foo" should not end up in the changelog as "ing foo", but FIX Fixing foo
should be  in the changelog as "Fixing foo"
Resolves #86
=> FIX Regex rules are improved to not match commit prefixes in words

composer.json, readme.md, src/Commands/Release/Changelog.php, src/Commands/Release/Release.php, src/Model/Changelog/Changelog.php, src/Model/Changelog/ChangelogItem.php, src/Steps/Release/CreateChangelog.php, tests/Model/Changelog/ChangelogItemTest.php, tests/Model/ChangelogTest.php
This will allow a CWP release to include all "other changes" in the changelog, for example:
```
* 2018-01-04 [afb33a9](https://github.com/symbiote/silverstripe-queuedjobs/commit/afb33a982c23dfb60a4fca2c1b52e8f58a5c8472) More SS4 cleanup (Daniel Hensby)
* 2017-02-14 [3dc2935](https://github.com/symbiote/silverstripe-queuedjobs/commit/3dc2935ee99361ddea7420c5fdfc3b8b353fdfaa) Add(queue) defaultJobs yml config for setting up a list of required jobs (Stephen McMahon)
```
The default behaviour will continue not to include these changes (since they aren't prefixed with a cow tag), but can optionally include them if needed.
Open to feedback, but if merged then resolves #88
=> NEW Add --all-commits option for changelog generation to categorise "Other changes"

src/Model/Modules/Library.php, src/Model/Release/LibraryRelease.php, src/Steps/Release/CreateChangelog.php, src/Steps/Release/PlanRelease.php, tests/Model/Release/LibraryReleaseTest.php
This allows the `.cow.pat.json` as the MVP to provide the `PriorVersion` for a module. This will be used in the cow plan and changelog, rather than guessing it from existing tags and constraints.
~I'd like to build this into the plan interface as well, but this was the minimum we wanted in order to be able to tweak plans occasionally for now~ (done). Resolves #87
=> NEW Cow plans can now specify prior versions of modules explicitly

src/Model/Modules/Library.php, src/Steps/Release/PlanRelease.php, tests/Model/Modules/LibraryTest.php
The prior version value was not being correctly saved to the plan. This patch ensures that it does.
Fixes #116
=> FIX PriorVersion value was not being saved to the cow plan

src/Commands/Release/Release.php, src/Steps/Release/BuildArchive.php, src/Steps/Release/CreateProject.php, src/Utility/Composer.php
Implement composer config.platform to emulate lowest requirements of PHP and extensions.
Thus, if composer defines requirement for php>=5.6, composer.lock will be built for PHP 5.6 even if you run cow on the system with php 7.2
Fixes #80
=> Align composer config platform with requirements

.travis.yml, src/Commands/GitHub/RateLimit.php, src/Model/Changelog/Changelog.php, src/Model/Modules/Project.php, src/Model/Modules/Theme.php, src/Steps/Release/CreateChangelog.php, src/Steps/Release/CreateProject.php, src/Steps/Release/RewriteReleaseBranches.php, src/Steps/Release/UpdateTranslations.php, src/Utility/Format.php, tests/Utility/Filter/SupportedModuleFilterTest.php
For some reason in PHP 7.2 Travis builds the timestamp diff is being converted to 4 minutes instead of 5 minutes in RateLimitTest. This massages the timestamp by a second to help it round to 5 minutes.
=> FIX Rounding error in PHP 7.2 for rate limit timestamp difference in minutes

src/Steps/Release/CreateChangelog.php
=> FIX Cow can now generate historic changelogs from and to pre-existing tags

src/Model/Modules/Library.php, tests/Model/Modules/LibraryTest.php
Commits from repositories with ssh remotes (e.g. when using VCS forks) don't resolve the repo URLs in the changelogs. This fixes that.
=> FIX Changelog generation now handles SSH remotes when finding repository URL

src/Model/Changelog/ChangelogItem.php, tests/Model/Changelog/ChangelogItemTest.php
Resolves https://github.com/silverstripe/cow/issues/131
=> NEW Cow now supports CVE identifiers in security commits when categorising commits in changelogs

.gitignore, docker/Dockerfile, docker/docker-compose.yml, docker/entrypoint.sh, docker/run, readme.md
This PR adds an alternative way to install COW locally. That means you don't have to install (and keep updated) all the dependencies natively on your host machine: `php`, `python`, `ruby`, `transifex-client`, `pip`, `yamlclean`, `satis` etc.
The only requirement for that setup would be docker itself and docker-compose.
This doesn't prevent you from installing everything natively on the host machine, just gives another option.
That's the setup I've been using locally for the last couple of releases, so I decided to share it.
This particular PR doesn't cover the publishing use case (e.g. the container doesn't have API keys, nor ssh-keys in the current config), but I think that could be covered by another PR in the future.
=> Add docker configs, docker/cow script

docker/.env, docker/Dockerfile, docker/README.md, docker/dbg, docker/dbg-test, docker/docker-compose.yml, docker/entrypoint.sh, docker/phpcs, docker/run, docker/test, readme.md
Adds xdebug capability to the docker container so it's debuggable by a localhost IDE.
The debug mode should work seamlessly for 127.0.0.1:9000 by running `./cow/docker/dbg` script (syntactically identical to `./cow/docker/run` and to `./cow/bin/cow`)
=> Docker config add xdebug capability

src/Steps/Release/PublishRelease.php
Allows releasing detached modules (e.g. when a module head is not a branch, but rather a custom cherry-picked change)
=> FIX detached modules release

src/Model/Release/Version.php, src/Utility/ChangelogRenderer.php, src/Utility/Template.php
We have a need to get more specific context on the release version in changelog templates - in particular, we want to output different content if the release is unstable. This tweak provides the release's full `Version` object to the template so that any exposed methods can be called on it.
Conveniently, the `Version` object implements `__toString()` so this change is completely backwards compatible with existing changelog templates.
This PR also includes a fix that halts execution if an exception is raised during changelog generation.
=> NEW Expose full release version object to changelog template

dockerhub/Dockerfile, dockerhub/README.md, readme.md
Create a /dockerhub version of docker that integrates with dockerhubs automated build tooling
Core idea is that we host an image on dockerhub and pull that down when we need to do things with cow. This is different from the existing solution in /docker where a fresh image of docker is built locally which will have different versions of things
The images in dockerhub are updatable by updating the Dockerfile on the master branch. Also, adding a semver tag on this repo will create a corresponding tagged version in dockerhub
Was previously in this PR https://github.com/silverstripe/cow/pull/158
=> Use dockerhub to host image

src/Commands/Release/Release.php, src/Model/Modules/Library.php, src/Steps/Release/CreateChangelog.php, src/Steps/Release/PlanRelease.php
This PR:
- Updates `release:plan` to include upgrade-only modules in both its plan UI and the resulting `.cow.pat.json` file. This allows us to selectively filter upgrade-only modules in other contexts.
- This also includes a tweak to the Library serialize method to include a read-only `'UpgradeOnly'` flag in the output, which will help external visualisation tools discern between modules marked as upgrade-only and not.
- Adds a new parameter to `release:changelog`, `--include-upgrade-only`, which will avoid filtering out upgrade-only modules during changelog generation.
The goal of this PR is to introduce the ability to provide complete changelogs to auditors without manual work.
Resolves #96.
=> Add `include-upgrade-only` flag for `release:changelog` to include `upgrade-only` changes to the changelog

docker/README.md, docker/bin/release, docker/entrypoint.sh
- Make the release command use the host code base (same as `run`, which is more natural behaviour)
- Add checks for GITHUB_API_TOKEN
- Allow to configure GITHUB_API_TOKEN though both `bin/composer config and the host environment variable)
=> Docker setup / tune the release command

.travis.yml, composer.json, readme.md, src/Application.php, src/Commands/Release/Changelog.php, src/Commands/Release/Release.php, src/Model/Changelog/Changelog.php, src/Model/Changelog/ChangelogItem.php, src/Steps/Release/CreateChangelog.php, src/Utility/Twig/Environment.php, src/Utility/Twig/Loader.php, templates/cow/changelog/logs/audit_mode.md.twig, templates/cow/changelog/logs/by_module.md.twig, templates/cow/changelog/logs/macros.md.twig, templates/cow/changelog/logs/plain.md.twig, templates/tests/base.twig, tests/Model/Changelog/ChangelogItemTest.php, tests/Model/ChangelogTest.php, tests/Steps/CreateChangelogTest.php, tests/Utility/Twig/EnvironmentTest.php
New format for changelog logs, using Twig templates.
Requires
- https://github.com/silverstripe/cow/pull/188
- https://github.com/silverstripe/cow/pull/190
Changelog examples:
- [changelog--audit-mode](https://gist.github.com/dnsl48/4d2b93225fb285f983d007266601341a)
- [new default for recipes](https://gist.github.com/dnsl48/ee2ea5731f0ee52a2cf45c344beaa19d)
--------------------------------------------------------------------------------------------
Resolves #186
Resolves #139
=> New changelog formats via Twig templates

src/Steps/Release/UpdateTranslations.php
Makes translation updates fall into "Other changes" section in changelogs.
=> Remove ENH prefix for translation commits

src/Utility/ChangelogRenderer.php
This was causing the first line of the changelog to be combined with the top delimiter comment, resulting in mangled rendering.
=> FIX Retain newlines between top delimiter and changelog

.github/workflows/docker-image-publish.yml, docker/Dockerfile, docker/release/Dockerfile, readme.md
Trying to use 7.3 caused issues as that's no longer supported by the modules.
Removed satis - ^1.0 is incompatible with the version of twig required by cow, and there is no stable 2.x release yet. Satis isn't actually used at all though.
Also update github action and Dockerfile to use ghcr.io (see https://docs.github.com/en/packages/working-with-a-github-packages-registry/migrating-to-the-container-registry-from-the-docker-registry) so we don't need to add a github token to docker just to download the package.
=> FIX Update docker image to use php 7.4

.github/workflows/docker-image-publish.yml
Fixes https://github.com/silverstripe/cow/actions/runs/2224048089
=> FIX Avoid deprecated use of unsafe set-env in github actions

src/Steps/Release/UpdateTranslations.php
Fixes this sort of thing that started happening after translations on js/json started working again after [this PR](https://github.com/silverstripe/cow/pull/203) was merged
=> FIX Handle unicode translations in json

src/Model/Changelog/ChangelogItem.php, src/Steps/Release/CreateChangelog.php, templates/cow/changelog/logs/macros.md.twig
Issue https://github.com/silverstripe/cow/issues/199
**If you have a `/tmp/cow/twig` folder you MUST `rm -rf` the folder first so the new twig template changes are picked up.**  I'll update the release process to note this
You can test HTML messages render as `Update README&amp;lt;a&amp;gt;my html&amp;lt;/a&amp;gt; lorem (Aaron Carlino)`
You can test this by updating `ChangelogItem.php`
```
public function getRawMessage()
{
return $this->getCommit()->getSubjectMessage() . '<a>my html</a> lorem';
}
```
=> FIX Prevent double escaping

composer.json
Fixes composer dependency problems in PHP linting job for `silverstripe/silverstripe-behat-extension`:
https://github.com/silverstripe/silverstripe-behat-extension/runs/7350017746?check_suite_focus=true
Job is failing because `silverstripe/silverstripe-behat-extension` requires `behat/behat ^3.9` which in turn requires `symfony/yaml` >= 4
- https://github.com/silverstripe/cow/pull/219
- https://github.com/silverstripe/gha-ci/issues/37
=> DEP Update symfony/yaml dependency

composer.json
Follow-up to https://github.com/silverstripe/cow/pull/218
Fixes composer dependency problems in PHP linting job for `silverstripe/silverstripe-behat-extension`:
https://github.com/silverstripe/silverstripe-behat-extension/runs/7404200666?check_suite_focus=true
I missed this when doing the first one - but behat/behat requires symfony/console of at least 4.x
This change is safe - none of the remove functionality according to [the changelog](https://github.com/symfony/console/blob/6.1/CHANGELOG.md) is being used.
=> DEP Update symfony/console dependency

README.md, src/Steps/Release/PublishRelease.php, src/Utility/GitHubApi.php
I had issues with my github token because it wasn't using the .env file to fetch it. This resulted in confusion when the release notes API returned 404 (which is for insufficient token permissions).
- https://github.com/silverstripeltd/product-issues/issues/691
=> ENH Allow using .env file for github token

src/Model/Changelog/ChangelogItem.php
If you have two commits on the same day with the same message, cow thinks they are duplicate and removes one.
=> BUG Treat commit with same message as distinct if they are on different seconds

src/Model/Changelog/ChangelogItem.php, tests/Model/Changelog/ChangelogItemTest.php
Noticed this in passing while reviewing another change. We sometimes use this old format for security vulnerabilities that we can't issue CVEs for, such as [SS-2023-001](https://www.silverstripe.org/download/security-releases/SS-2023-001)
Not sure why this was ever changed to mark them as "other" changes, but we definitely do treat these the same as we do with security issues we _can_ assign CVEs to.
- https://github.com/silverstripeltd/product-issues/issues/805
=> FIX Add SS-2023-001 style security commits.

src/Application.php, src/Model/Changelog/ChangelogItem.php, templates/cow/changelog/logs/audit_mode.md.twig, templates/cow/changelog/logs/by_module.md.twig, templates/cow/changelog/logs/plain.md.twig
Issue https://github.com/silverstripe/.github/issues/135
There's also an additional commit in here to disable the twig caching which is annoying as it requires the user to `rm -rf /tmp/cow/twig/cache` in order to get the twig template changes. Given this is so easy to miss it may mean we accidentally leave out the translation commits in a changelog in the future.  There is seemingly zero performance difference with the caching disabled
The test this I created mock 5.1.1 release - I made this a patch release to ensure I didn't accidentally create new 5.2 branches
- ensure cow .env file has DEV_MODE=1
- cow release:create -vvv 5.1.1 silverstripe/recipe-kitchen-sink
- cow release:plan -vvv 5.1.1 silverstripe/recipe-kitchen-sink
- Update the readme in framework and add a commit 'TLN My …
=> ENH Handle TLN commit prefix

src/Model/Changelog/Changelog.php, src/Model/Changelog/ChangelogItem.php, src/Utility/ChangelogRenderer.php, templates/cow/changelog/logs/by_module.md.twig, templates/cow/changelog/logs/macros.md.twig, templates/cow/changelog/logs/plain.md.twig, tests/Model/ChangelogTest.php
Tested this with a dummy run and it works well.
Some commit messages may still introduce unexpected linting issues - we can look at whether the current set of rule exclusions is appropriate if/when that happens, but for now those rules are the only ones that need excluding. I don't want to exclude linting altogether for them in case some commit message has something which would result in poorly rendered markdown.
- https://github.com/silverstripe/silverstripe-admin/issues/1544
=> FIX Ensure changelog passes linting

src/Steps/Release/PublishRelease.php
Issue https://github.com/silverstripeltd/product-issues/issues/844
In the console log it prefixes the tag with v, which is wrong and makes it look like cow is doing something bad
=> ENH Do not prefix tag with v

composer.json, src/Model/Changelog/ChangelogItem.php, tests/Model/Changelog/ChangelogItemTest.php
Issue https://github.com/silverstripeltd/product-issues/issues/844
There was a `__CLASS__ ` in one of the PR titles. The new markdown linter didn't like this
=> FIX Handle double underscored PR titles in changelog

src/Steps/Release/PublishRelease.php
Issue https://github.com/silverstripe/cow/issues/253
Tested locally by creating a new fake release with `DEV_MODE=1` in my `.env` file and adding `echo("$name\n");return;` to `PublishRelease::releaseLibrary()` to show the order that modules would be released in
**Before:**
```
silverstripe/assets
silverstripe/config
silverstripe/framework
...
silverstripe/developer-docs
...
silverstripe/recipe-kitchen-sink
```
**After:**
```
silverstripe/developer-docs
silverstripe/assets
silverstripe/config
silverstripe/framework
...
silverstripe/recipe-kitchen-sink
```
I've double checked that `silverstripe/developer-docs` only appears once in the "after" list
=> ENH Publish developer-docs before other modules

src/Model/Modules/Library.php, src/Steps/Release/PublishRelease.php
If an error occurs when cow has already tagged 15 repos, we want to be able to rerun the release command and skip anything we've already tagged.
- https://github.com/silverstripeltd/product-issues/issues/877
=> ENH Skip repositories we've already tagged

src/Commands/Release/MergeUp.php, src/Model/Release/ComposerConstraint.php, src/Steps/Release/MergeUpRelease.php, src/Steps/Release/RewriteReleaseBranches.php, src/Utility/ConstraintStabiliser.php
Also remove references to the defunct `*-release` branch naming convention
- https://github.com/silverstripe/.github/issues/407
=> ENH Remove CMS 4 workarounds
