- src/Commands/Release/Changelog.php
- src/Commands/Release/Release.php
- src/Model/Changelog.php
- src/Model/ChangelogItem.php
- src/Steps/Release/CreateChangelog.php
> Standardise case on references to "Changelog"

- src/Model/ChangelogItem.php
Changelogs were missing commits such as https://github.com/silverstripe-australia/silverstripe-advancedworkflow/pull/289
> BUG Make check for "BUG" tags case-insensitive

- src/Steps/Module/TagAnnotatedModule.php
If there's no github token environment variable, then try to use the one composer possibly has
> NEW Try to get GitHub oAuth token from composer

- readme.md
- src/Application.php
- src/Commands/Release/Create.php
- src/Commands/Release/Plan.php
- src/Model/Modules/Library.php
- src/Model/Release/Version.php
- src/Steps/Release/PlanRelease.php
- src/Steps/Release/PublishRelease.php
- src/Steps/Release/UpdateTranslations.php
- tests/Model/Release/VersionTest.php
Fixes a bug in project creation and allows non-stable releases to include RC tagged dependencies.
> Fixes to cow for CWP release

- src/Commands/Release/Release.php
> FIX Skip-tests option now works

- src/Application.php
> FIX Remove reference to removed class

- src/Steps/Release/BuildArchive.php
Merging to 1 branch, since this feature isn't re-written for 2.0 yet.
> Remove asset-admin for framework-only

- composer.json
- src/Steps/Release/PublishRelease.php
> BUG Fix breaking changes in github client library

- composer.json
Also if you have time once you get back from holiday, @dhensby :)
> API Upgrade to symfony 3

- src/Commands/Release/Create.php
- src/Commands/Release/Publish.php
- src/Commands/Release/Release.php
- src/Steps/Release/BuildArchive.php
- src/Steps/Release/CreateProject.php
- src/Steps/Release/Wait.php
This is a horrible way to do it imo, but kinda works.
Basically, use `cow release [version] --repository=[link to composer repo]`
> NEW Allow defining custom repositories for releases

- readme.md
- src/Commands/Release/Publish.php
- src/Commands/Release/Release.php
- src/Steps/Release/BuildArchive.php
- src/Steps/Release/CreateProject.php
- src/Steps/Release/UpdateTranslations.php
- src/Utility/Composer.php
@dhensby I've done a manual merge of 1 branch into master; Notably I've had to manually re-write https://github.com/silverstripe/cow/pull/27 in order to get it to fit (most of it was already a part of master).
Do you want to confirm I've merged it up correctly?
> 1 to 2 merge

- src/Commands/Release/Archive.php
- src/Utility/Composer.php
To go with https://github.com/silverstripe/silverstripe-framework/pull/7681
> BUG Fix --repository so that it actually works

- src/Utility/Composer.php
Fixes https://github.com/silverstripe/silverstripe-framework/issues/7709
> ENHANCEMENT New projects will set config.platform.php to that specified by root requirements

- src/Model/Modules/Library.php
- src/Model/Modules/Project.php
- src/Model/Release/LibraryRelease.php
- src/Model/Release/Version.php
- src/Steps/Release/CreateProject.php
- src/Steps/Release/PlanRelease.php
- src/Steps/Release/PublishRelease.php
- src/Utility/Composer.php
* Fix to support duplicated libraries in the release
* ignore-platform-deps but only on base install project
* Ensure cache is cleared to prevent tags being missed on install
> Fixup for cwp 2.0 issues

- src/Steps/Release/PublishRelease.php
Prevents modules doing this (oops!) https://github.com/silverstripe/silverstripe-comments/commit/1da927fa02016a2aaab3151c9577d944bc663dc5
> BUG Fix non-library modules fixing their dependencies on tag

- src/Steps/Release/UpdateTranslations.php
> API Deprecate checkTransifexVersion and remove its logic, to be removed in 3.0

- src/Model/Modules/Library.php
- tests/Model/Modules/LibraryTest.php
> NEW Add friendlier error message when project does not exist

- cow-schema.md
- cow.schema.json
- src/Commands/Release/Release.php
- src/Model/Modules/Library.php
- src/Steps/Release/CreateChangelog.php
- tests/Model/Modules/LibraryTest.php
> NEW --include-other-changes can now be read from project-level Cow configuration

- src/Commands/Command.php
- src/Commands/Release/Branch.php
- src/Commands/Release/Changelog.php
- src/Commands/Release/Plan.php
- src/Commands/Release/Release.php
- src/Commands/Release/Translate.php
- src/Model/Release/LibraryRelease.php
- src/Steps/Release/PlanRelease.php
- tests/Model/Release/LibraryReleaseTest.php
Also added a countAllItems() method since counting a generator requires a loop.
Technically a major change due to the constructor signature change.
Resolves #76
> NEW Planning a release now shows a progress indicator

- src/Commands/Module/Sync/Metadata.php
- src/Commands/Release/Branch.php
- src/Model/Changelog/Changelog.php
- src/Model/Modules/Library.php
- src/Model/Release/Version.php
- src/Utility/ChangelogRenderer.php
- src/Utility/Filter/SupportedModuleFilter.php
- src/Utility/GitHubApi.php
- src/Utility/SchemaValidator.php
Just making the tests green again
> Some PSR-12 fixes

- src/Application.php
- src/Commands/Release/DetachTaggedBase.php
- src/Model/Release/Version.php
- src/Steps/Release/DetachTaggedBase.php
> release:detach-tagged-base command initial implementation

- docker/bin/composer
- docker/docker-compose.yml
- docker/entrypoint.sh
- readme.md
follow up on https://github.com/silverstripe/cow/issues/163
> Docker / fix bin/tx, preserve composer configs, update the documentation

- src/Commands/Release/Release.php
- src/Model/Changelog/ChangelogItem.php
- src/Steps/Release/CreateChangelog.php
- Fix include-update-only flag
- Relax CVE detection rules in the commit messages (square brackets are not mandatory)
> Fix changelog generation

- src/Steps/Release/RewriteReleaseBranches.php
Less scary language =)
Also say module instead of library since that's what how we normally refer to things
> Say branching not releasing

- src/Steps/Release/DetachTaggedBase.php
- Adds support for `upgrade-only` modules to DetachTaggedBase
- Fix identifying the correct version for modules retaining the version in the plan (no release)
> FIX UpgradeOnly support for DetachTaggedBase

- .travis.yml
- composer.json
- src/Steps/Release/PublishRelease.php
Issue https://github.com/silverstripe/silverstripe-framework/issues/10253
> DEP Use guzzle 7

- src/Steps/Release/UpdateTranslations.php
Avoid removing translation keys that exist in yml or json but don't exist in transifex.
There was no code to merge yaml keys, so `tx pull` was always overriding the yaml content entirely.
There was code to merge json keys, but it was looking for `src/en.js` specifically, which doesn't exist. Instead, it should look for all `.json` files in the `src/` directory of each module's js lang directories.
Also removed `ksort` of the json content as per the discussion in the issue.
fixes #202
> FIX Make release:translate non destructive

- src/Model/Modules/Library.php
- src/Model/Release/ComposerConstraint.php
- src/Model/Release/LibraryRelease.php
- src/Model/Release/Version.php
- src/Steps/Release/CreateChangelog.php
- src/Steps/Release/PublishRelease.php
- tests/Steps/PublishReleaseTest.php
- No need for modules to include specific config - just always do it.
- Get release notes from GitHub API
- https://github.com/silverstripe/cow/issues/184
> ENH Always create a github release when tagging a new release

- .github/workflows/ci.yml
- .github/workflows/keepalive.yml
- readme.md
Issue https://github.com/silverstripe/gha-ci/issues/11<br /><br />Workflow run https://github.com/creative-commoners/cow/actions?query=branch%3Apulls%2Fmaster%2Fmodule-standards
> MNT Use GitHub Actions CI

- composer.json
- src/Steps/Release/PublishRelease.php
- src/Steps/Release/RewriteReleaseBranches.php
- src/Utility/CommandRunner.php
- src/Utility/Format.php
- src/Utility/Translations.php
- tests/Steps/PublishReleaseTest.php
Fixes linting issue in CI: https://github.com/silverstripe/cow/runs/7403857128?check_suite_focus=true
Also add dependency for `php-http/discovery` with lowest version that supports guzzle 7 https://github.com/php-http/discovery/blob/master/CHANGELOG.md#1120---2020-09-22 to fix failing prefer-lowest job
> MNT Run phpcbf to fix linting issues

- composer.json
- src/Model/Modules/Library.php
- src/Model/Release/LibraryRelease.php
- src/Steps/Release/CreateChangelog.php
- src/Steps/Release/PlanRelease.php
- src/Steps/Release/PublishRelease.php
- src/Utility/ConstraintStabiliser.php
Issue https://github.com/silverstripe/cow/issues/227 - Modules added to recipes aren't included in changelogs for their first release
Issue https://github.com/silverstripe/cow/issues/236 - Some recipe constraints not getting updated
There are separate commits for the separate issues
> FIX Changes for CMS 5 release

- src/Steps/Step.php
- src/Utility/CommandRunner.php
- src/Utility/Composer.php
- src/Utility/StepCommandRunner.php
Issue https://github.com/silverstripe/cow/issues/237
> ENH Do not output github token to console when -vvv is set

- cow-schema.md
Issue https://github.com/silverstripe/.github/issues/210
> FIX Update changelog path

- src/Model/Changelog/ChangelogItem.php
- tests/Model/Changelog/ChangelogItemTest.php
Issue https://github.com/silverstripe/.github/issues/410
Looking through the twig templates, short message is what is used in both the changelog templates
> ENH Escape short message if two ore more underscores
